name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run make setup
        run: make setup

      - name: Run make test
        run: make test

      - name: Run make lint
        run: make lint
